// src/lib/store/destinations/destinationData.ts
import { Destination, TravelPackage } from './types';

export const mockDestinations: Destination[] = [
  {
    id: '1',
    name: 'Bali',
    country: 'Indonesia',
    location: 'Bali',
    description: 'Paradise island with beautiful beaches, temples, and vibrant culture',
    image: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800',
    rating: 4.8,
    reviews: 2340,
    price: 45000,
    priceRange: 'moderate',
    duration: '5-7 days',
    category: 'Beach',
    tags: ['Beach', 'Culture', 'Adventure'],
    travelers: ['solo', 'couple', 'family'],
    season: ['spring', 'summer', 'autumn'],
    featured: true,
  },
  {
    id: '2',
    name: 'Paris',
    country: 'France',
    location: 'Paris',
    description: 'City of lights, romance, and world-class art and architecture',
    image: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800',
    rating: 4.9,
    reviews: 3520,
    price: 85000,
    priceRange: 'luxury',
    duration: '4-6 days',
    category: 'City',
    tags: ['Culture', 'Romantic', 'Art'],
    travelers: ['couple', 'solo', 'family'],
    season: ['spring', 'autumn'],
    featured: true,
  },
  {
    id: '3',
    name: 'Manali',
    country: 'India',
    location: 'Himachal Pradesh',
    description: 'Hill station in the Himalayas with stunning mountain views',
    image: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=800',
    rating: 4.6,
    reviews: 1890,
    price: 25000,
    priceRange: 'budget',
    duration: '3-5 days',
    category: 'Mountain',
    tags: ['Adventure', 'Nature', 'Trekking'],
    travelers: ['solo', 'couple', 'friends'],
    season: ['spring', 'summer', 'winter'],
    featured: true,
  },
  {
    id: '4',
    name: 'Dubai',
    country: 'UAE',
    location: 'Dubai',
    description: 'Modern city with luxury shopping, ultramodern architecture',
    image: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800',
    rating: 4.7,
    reviews: 2980,
    price: 65000,
    priceRange: 'luxury',
    duration: '4-6 days',
    category: 'City',
    tags: ['Luxury', 'Shopping', 'Modern'],
    travelers: ['couple', 'family', 'friends'],
    season: ['winter', 'spring'],
  },
  {
    id: '5',
    name: 'Kyoto',
    country: 'Japan',
    location: 'Kyoto',
    description: 'Ancient capital with traditional temples and beautiful gardens',
    image: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800',
    rating: 4.9,
    reviews: 2150,
    price: 75000,
    priceRange: 'moderate',
    duration: '5-7 days',
    category: 'Cultural',
    tags: ['Culture', 'History', 'Temples'],
    travelers: ['solo', 'couple'],
    season: ['spring', 'autumn'],
  },
  {
    id: '6',
    name: 'Maldives',
    country: 'Maldives',
    location: 'Maldives',
    description: 'Tropical paradise with crystal-clear waters and luxury resorts',
    image: 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=800',
    rating: 4.9,
    reviews: 3210,
    price: 120000,
    priceRange: 'luxury',
    duration: '5-7 days',
    category: 'Beach',
    tags: ['Beach', 'Luxury', 'Honeymoon'],
    travelers: ['couple'],
    season: ['winter', 'spring'],
    featured: true,
  },
  {
    id: '7',
    name: 'Swiss Alps',
    country: 'Switzerland',
    location: 'Swiss Alps',
    description: 'Majestic mountains with world-class skiing and scenic views',
    image: 'https://images.unsplash.com/photo-1531366936337-7c912a4589a7?w=800',
    rating: 4.8,
    reviews: 1670,
    price: 95000,
    priceRange: 'luxury',
    duration: '6-8 days',
    category: 'Mountain',
    tags: ['Adventure', 'Skiing', 'Nature'],
    travelers: ['couple', 'family', 'friends'],
    season: ['winter', 'summer'],
  },
  {
    id: '8',
    name: 'Serengeti',
    country: 'Tanzania',
    location: 'Serengeti',
    description: 'Wildlife safari destination with incredible animal diversity',
    image: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=800',
    rating: 4.7,
    reviews: 980,
    price: 110000,
    priceRange: 'luxury',
    duration: '7-10 days',
    category: 'Wildlife',
    tags: ['Safari', 'Wildlife', 'Adventure'],
    travelers: ['couple', 'family', 'friends'],
    season: ['summer', 'autumn'],
  },
];

export const mockPackages: TravelPackage[] = [
  {
    id: 'pkg1',
    destinationId: '1',
    title: 'Bali Paradise Package',
    description: 'Experience the best of Bali with this comprehensive tour',
    price: 45000,
    originalPrice: 55000,
    duration: '6 Days / 5 Nights',
    includes: ['4-Star Hotel', 'Daily Breakfast', 'Airport Transfers', 'Guided Tours'],
    highlights: ['Ubud Rice Terraces', 'Tanah Lot Temple', 'Beach Club Day Pass', 'Traditional Dance Show'],
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800',
    bestTimeToVisit: 'April - October',
  },
  {
    id: 'pkg2',
    destinationId: '2',
    title: 'Romantic Paris Getaway',
    description: 'Fall in love with the city of lights',
    price: 85000,
    originalPrice: 95000,
    duration: '5 Days / 4 Nights',
    includes: ['4-Star Hotel', 'Daily Breakfast', 'Seine River Cruise', 'Museum Passes'],
    highlights: ['Eiffel Tower', 'Louvre Museum', 'Versailles Palace', 'Montmartre Walking Tour'],
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800',
    bestTimeToVisit: 'April - June, September - October',
  },
  {
    id: 'pkg3',
    destinationId: '3',
    title: 'Manali Adventure Escape',
    description: 'Thrilling mountain adventures in the Himalayas',
    price: 25000,
    duration: '4 Days / 3 Nights',
    includes: ['3-Star Hotel', 'Daily Meals', 'Adventure Activities', 'Local Transport'],
    highlights: ['Solang Valley', 'Rohtang Pass', 'River Rafting', 'Paragliding'],
    rating: 4.6,
    image: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=800',
    bestTimeToVisit: 'October - June',
  },
  {
    id: 'pkg4',
    destinationId: '6',
    title: 'Maldives Luxury Retreat',
    description: 'Ultimate luxury in an overwater villa',
    price: 120000,
    originalPrice: 140000,
    duration: '6 Days / 5 Nights',
    includes: ['5-Star Resort', 'All Meals Included', 'Water Sports', 'Spa Treatments'],
    highlights: ['Overwater Villa', 'Private Beach', 'Snorkeling', 'Sunset Cruise'],
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=800',
    bestTimeToVisit: 'November - April',
  },
];
